// frontend/src/pages/Login.tsx
import { createSignal, Show } from "solid-js";
import { useNavigate, A } from "@solidjs/router";
import { useMutation } from "@tanstack/solid-query";
import { api, ApiError } from "../api/client";
import { TextField, PrimaryButton, ErrorState } from "../components/ui";

export default function Login() {
  const navigate = useNavigate();
  const [email, setEmail] = createSignal("");
  const [password, setPassword] = createSignal("");
  const [errors, setErrors] = createSignal<Record<string, string>>({});
  const [formError, setFormError] = createSignal("");

  const login = useMutation(() => ({
    mutationFn: () => api.post("/auth/login", { email: email(), password: password() }),
    onSuccess: () => navigate("/jemaat", { replace: true }),
    onError: (err) => {
      if (err instanceof ApiError && err.fieldErrors) setErrors(err.fieldErrors);
      else setFormError(err instanceof Error ? err.message : "Gagal masuk");
    },
  }));

  const submit = (e: Event) => {
    e.preventDefault();
    setErrors({});
    setFormError("");
    login.mutate();
  };

  return (
    <div class="flex min-h-screen items-center justify-center px-4">
      <div class="w-full max-w-sm">
        <h1 class="mb-1 text-3xl font-bold tracking-tight text-ink">Masuk</h1>
        <p class="mb-6 text-sm text-ink-soft">Kelola data gereja Anda</p>
        <form onSubmit={submit} class="space-y-4 rounded-2xl border border-line bg-surface-raised p-6 shadow-sm">
          <Show when={formError()}>
            <ErrorState message={formError()} />
          </Show>
          <TextField
            label="Email"
            type="email"
            autocomplete="email"
            value={email()}
            onInput={(e) => setEmail(e.currentTarget.value)}
            error={errors().Email}
            required
          />
          <TextField
            label="Kata Sandi"
            type="password"
            autocomplete="current-password"
            value={password()}
            onInput={(e) => setPassword(e.currentTarget.value)}
            error={errors().Password}
            required
          />
          <PrimaryButton type="submit" loading={login.isPending} class="w-full">
            Masuk
          </PrimaryButton>
        </form>
        <p class="mt-4 text-center text-sm text-ink-soft">
          Belum punya akun?{" "}
          <A href="/signup" class="font-semibold text-sage-700 hover:underline">
            Daftar
          </A>
        </p>
      </div>
    </div>
  );
}

// frontend/src/routes/Login.svelte
<script lang="ts">
  import Button from '$lib/components/ui/Button.svelte';
  import Input from '$lib/components/ui/Input.svelte';
  import Label from '$lib/components/ui/Label.svelte';
  import { auth } from '$lib/stores/auth.svelte';
  import { t } from '$lib/i18n';
  import { push } from 'svelte-spa-router';
  import { onMount } from 'svelte';

  let email = $state('');
  let password = $state('');

  onMount(() => {
    if (auth.isAuthenticated) {
      push('/');
    }
  });

  function handleSubmit(e: Event) {
    e.preventDefault();
    auth.login(email, password);
  }
</script>

<div class="flex min-h-screen items-center justify-center bg-muted/30 p-4">
  <form
    class="w-full max-w-sm space-y-4 rounded-lg border bg-card p-8 shadow-sm"
    onsubmit={handleSubmit}
  >
    <div class="space-y-1">
      <h1 class="text-2xl font-semibold">Shepherd</h1>
      <p class="text-sm text-muted-foreground">
        {t('login.subtitle', 'Masuk ke akun gereja Anda.')}
      </p>
    </div>

    {#if auth.loginError}
      <p class="rounded-md border border-destructive/50 bg-destructive/5 px-3 py-2 text-sm text-destructive">
        {auth.loginError}
      </p>
    {/if}

    <div class="space-y-1.5">
      <Label for="email">{t('login.email', 'Email')}</Label>
      <Input
        id="email"
        type="email"
        required
        autocomplete="email"
        bind:value={email}
      />
    </div>

    <div class="space-y-1.5">
      <Label for="password">{t('login.password', 'Password')}</Label>
      <Input
        id="password"
        type="password"
        required
        autocomplete="current-password"
        bind:value={password}
      />
    </div>

    <Button type="submit" class="w-full" disabled={auth.isLoading}>
      {auth.isLoading ? t('login.loading', 'Masuk…') : t('login.submit', 'Masuk')}
    </Button>

    <p class="text-center text-xs text-muted-foreground">
      Hubungi admin untuk membuat akun gereja baru.
    </p>
  </form>
</div>
