// frontend/src/lib/components/ui/Select.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { cn } from '$lib/utils/cn';

  interface Props {
    name?: string;
    id?: string;
    value?: string | number | null;
    required?: boolean;
    disabled?: boolean;
    class?: string;
    onchange?: (e: Event) => void;
    children?: Snippet;
  }

  let {
    name,
    id,
    value = $bindable(''),
    required = false,
    disabled = false,
    class: className = '',
    onchange,
    children,
  }: Props = $props();

  const cls = cn(
    'flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50',
    className,
  );
</script>

<select {name} {id} {required} {disabled} bind:value class={cls} {onchange}>
  {@render children?.()}
</select>

// apps/web/src/components/ui/select.tsx
import { ChevronDown } from 'lucide-react';
import * as React from 'react';
import { cn } from '@/lib/utils';

/** Native select styled to match inputs; native pickers give the best mobile experience. */
function Select({ className, children, ...props }: React.ComponentProps<'select'>) {
  return (
    <div className="relative">
      <select
        data-slot="select"
        className={cn(
          'flex h-11 w-full appearance-none rounded-lg border border-input bg-card py-2 pr-10 pl-3.5 text-base text-foreground shadow-xs transition-[color,box-shadow] outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/30 disabled:cursor-not-allowed disabled:opacity-50 aria-invalid:border-destructive md:text-sm',
          className,
        )}
        {...props}
      >
        {children}
      </select>
      <ChevronDown
        aria-hidden
        className="pointer-events-none absolute top-1/2 right-3 size-4 -translate-y-1/2 text-muted-foreground"
      />
    </div>
  );
}

export { Select };
