// frontend/src/components/ui/input.tsx
import { type InputHTMLAttributes, forwardRef } from "react";
import { cn } from "../../lib/utils";

export const Input = forwardRef<HTMLInputElement, InputHTMLAttributes<HTMLInputElement>>(
  ({ className, ...props }, ref) => (
    <input
      ref={ref}
      className={cn(
        "flex h-10 w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gray-400 disabled:opacity-50",
        className,
      )}
      {...props}
    />
  ),
);
Input.displayName = "Input";

// frontend/src/lib/components/ui/Input.svelte
<script lang="ts">
  import type { HTMLInputAttributes } from 'svelte/elements';
  import { cn } from '$lib/utils/cn';

  interface Props {
    type?: string;
    name?: string;
    id?: string;
    placeholder?: string;
    value?: string | number | null;
    required?: boolean;
    disabled?: boolean;
    class?: string;
    autocomplete?: HTMLInputAttributes['autocomplete'];
    oninput?: (e: Event) => void;
    onchange?: (e: Event) => void;
  }

  let {
    type = 'text',
    name,
    id,
    placeholder,
    value = $bindable(''),
    required = false,
    disabled = false,
    class: className = '',
    autocomplete,
    oninput,
    onchange,
  }: Props = $props();

  const cls = cn(
    'flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50',
    className,
  );
</script>

<input
  {type}
  {name}
  {id}
  {placeholder}
  {required}
  {disabled}
  {autocomplete}
  bind:value
  class={cls}
  {oninput}
  {onchange}
/>
