// frontend/src/components/ui/select.tsx
import { type SelectHTMLAttributes, forwardRef } from "react";
import { cn } from "../../lib/utils";

// Select is a styled native <select>; it works directly with react-hook-form's
// register() and needs no portal or focus-trap work.
export const Select = forwardRef<HTMLSelectElement, SelectHTMLAttributes<HTMLSelectElement>>(
  ({ className, children, ...props }, ref) => (
    <select
      ref={ref}
      className={cn(
        "flex h-10 w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gray-400 disabled:opacity-50",
        className,
      )}
      {...props}
    >
      {children}
    </select>
  ),
);
Select.displayName = "Select";

// frontend/src/lib/components/ui/Select.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { cn } from '$lib/utils/cn';

  interface Props {
    name?: string;
    id?: string;
    value?: string | number | null;
    required?: boolean;
    disabled?: boolean;
    class?: string;
    onchange?: (e: Event) => void;
    children?: Snippet;
  }

  let {
    name,
    id,
    value = $bindable(''),
    required = false,
    disabled = false,
    class: className = '',
    onchange,
    children,
  }: Props = $props();

  const cls = cn(
    'flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50',
    className,
  );
</script>

<select {name} {id} {required} {disabled} bind:value class={cls} {onchange}>
  {@render children?.()}
</select>
