// frontend/src/lib/components/ui/Label.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { cn } from '$lib/utils/cn';

  interface Props {
    for?: string;
    class?: string;
    children?: Snippet;
  }

  const { for: htmlFor, class: className = '', children }: Props = $props();
</script>

<label for={htmlFor} class={cn('text-sm font-medium leading-none text-foreground', className)}>
  {@render children?.()}
</label>

// frontend/src/components/ui/label.tsx
import { type LabelHTMLAttributes, forwardRef } from "react";
import { cn } from "../../lib/utils";

export const Label = forwardRef<HTMLLabelElement, LabelHTMLAttributes<HTMLLabelElement>>(
  ({ className, ...props }, ref) => (
    <label ref={ref} className={cn("text-sm font-medium text-gray-900", className)} {...props} />
  ),
);
Label.displayName = "Label";
